# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inherit! :search_paths
  pod 'app', :path => '../app'
end
